export const data = [
    // {
    //     "id": 1,
    //     "title": "Space Tourism multi-page website",
    //     "html": "HTML",
    //     "css": "CSS",
    //     "js": "JS",
    //     "level": 3,
    //     "levelName": "INTERMEDIATE",
    //     "text": "This project is a fun collaboration with Scrimba and Kevin Powell! If you like, you can follow along and watch Kevin complete the project on Scrimba. Lots to learn!",
    //     "imgURI": "/images/space/space.jpg",
    //     "location":"/profile-card"
    // },
    {
        "id": 2,
        "title": "E-commerce product page",
        "html": "HTML",
        "css": "CSS",
        "js": "JS",
        "level": 3,
        "levelName": "INTERMEDIATE",
        "text": "In this challenge, you'll build a beautiful product page. We'll be putting your JS skills to the test with a lightbox product gallery and cart functionality!",
        "imgURI":"/images/ecom-shoe/ecom.jpg",
        "location": "/ecommerce"
    },
    {
        "id": 3,
        "title": "Order summary component",
        "html": "HTML",
        "css": "CSS",
        "level": 1,
        "levelName": "NEWBIE",
        "text": "A perfect project for newbies who are starting to build confidence with layouts!",
        "imgURI": "/images/order/order.jpg",
        "location": "/summary"
    },
    {
        "id": 4,
        "title": "Sunnyside agency landing page",
        "html": "HTML",
        "css": "CSS",
        "js": "JS",
        "level": 2,
        "levelName": "JUNIOR",
        "text": "This challenge will be a perfect test of your layout and responsive skills. There's a tiny bit of JS for the mobile menu, but the focus is HTML & CSS.",
        "imgURI": "/images/sunnyside/sunnyside.jpg",
        "location":"/sunny-side"
    },
    {
        "id": 5,
        "title": "Loopstudios landing page",
        "html": "HTML",
        "css": "CSS",
        "js": "JS",
        "level": 3,
        "levelName": "INTERMEDIATE",
        "text": "This challenge is perfect if you're looking to test your CSS Grid chops. Even without Grid, this project will be a fun one to help you practice your layout skills!",
        "imgURI": "/images/loop-studios/loopstudio.jpg",
        "location":"/loop-studios"
    }, 
    {
        "id": 6,
        "title": "Profile card component",
        "html": "HTML",
        "css": "CSS",
        "level": 1,
        "levelName": "NEWBIE",
        "text": "This is a perfect challenge to test your layout skills. The card layout doesn't shift, so it's also great for those that haven't dived into responsive websites yet!",
        "imgURI": "/images/profilecard/profilecard.jpg",
        "location":"/profile-card"
    },
    {
        "id": 7,
        "title": "Stats Preview Card",
        "html": "HTML",
        "css": "CSS",
        "level": 1,
        "levelName": "NEWBIE",
        "text": "This is a great small challenge to help get you used to building to a design. There's no JS in this project, so you'll be able to focus on your HTML & CSS skills.",
        "imgURI": "/images/stats/stats.jpg",
        "location": "/stats-preview-card"
    },
    // {
    //     "id": 8,
    //     "title": "Crowd Funding",
    //     "html": "HTML",
    //     "css": "CSS",
    //     "level": 2,
    //     "levelName": "JUNIOR",
    //     "text": "This challenge will test both your layout and state management skills. As visitors make pledges, your goal is to keep track of the changes.",
    //     "imgURI": "/images/crowd-fund/crowd-fund.jpg",
    //     "location": "/crowd-fund"
    // },
    {
        "id": 9,
        "title": "Grid Testimonial",
        "html": "HTML",
        "css": "CSS",
        "level": 2,
        "levelName": "JUNIOR",
        "text": "This challenge will be perfect practice for anyone wanting to test their CSS Grid skills. Grid is such a powerful addition to CSS, so it's worth getting to grips with it!",
        "imgURI": "/images/testimonial/testimonial.jpg",
        "location": "/testimonial"
    },
    {
        "id": 10,
        "title": "Room homepage",
        "html": "HTML",
        "css": "CSS",
        "js": "JS",
        "level": 3,
        "levelName": "INTERMEDIATE",
        "text": "This challenge will be perfect practice for anyone wanting to test their CSS Grid skills. Grid is such a powerful addition to CSS, so it's worth getting to grips with it!",
        "imgURI": "/images/room/room.jpg",
        "location": "/room-homepage"
    },
    {
        "id": 11,
        "title": "Price Component",
        "html": "HTML",
        "css": "CSS",
        "level": 2,
        "levelName": "JUNIOR",
        "text": "This challenge will get you thinking about building an accessible custom toggle control and also test your layout skills.",
        "imgURI": "/images/price-component/price-component.jpg",
        "location": "/price-component"
    },
    {
        "id": 12,
        "title": "Insure landing page",
        "html": "HTML",
        "css": "CSS",
        "level": 2,
        "levelName": "JUNIOR",
        "text": "Test your layout skills with this HTML & CSS only landing page. This challenge is perfect if you're starting to get confident in laying out web pages.",
        "imgURI": "/images/insurance-landing/insurance-landing.jpg",
        "location": "/insurance-landing"
    },
    // {
    //     "id": 13,
    //     "title": "Todo app",
    //     "html": "HTML",
    //     "css": "CSS",
    //     "js": "JS",
    //     "level": 3,
    //     "levelName": "INTERMEDIATE",
    //     "text": "The classic todo app with a few twists! This app includes a dark/light theme toggle and drag & drop reordering for anyone wanting an extra test.",
    //     "imgURI": "/images/todo/todo.jpg",
    //     "location": "/todo"
    // },
    {
        "id": 14,
        "title": "Clipboard landing page",
        "html": "HTML",
        "css": "CSS",
        "level": 2,
        "levelName": "JUNIOR",
        "text": "Put your layout skills to the test with this HTML & CSS landing page challenge. This challenge includes a design for hover states.",
        "imgURI": "/images/clipboard-landing/clipboard-landing.jpg",
        "location": "/clipboard-landing"
    },
    {
        "id": 15,
        "title": "Launch countdown timer",
        "html": "HTML",
        "css": "CSS",
        "js": "JS",
        "level": 3,
        "levelName": "INTERMEDIATE",
        "text": "This will be a fun one! Your challenge is to build this countdown timer. There are lots of small CSS tests in the design as well. So it should keep you busy!",
        "imgURI": "/images/launch/launch.jpg",
        "location": "/launch"
    },
    {
        "id": 16,
        "title": "Manage landing page",
        "html": "HTML",
        "css": "CSS",
        "js": "JS",
        "level": 3,
        "levelName": "INTERMEDIATE",
        "text": "This challenge will be a great test for your responsive skills. There are lots of small details and slight content shifts for different screen sizes.",
        "imgURI": "/images/manage-landing/manage-landing.jpg",
        "location": "/manage-landing"
    },
    {
        "id": 17,
        "title": "Easybank landing page",
        "html": "HTML",
        "css": "CSS",
        "js": "JS",
        "level": 3,
        "levelName": "INTERMEDIATE",
        "text": "This challenge will provide a nice test for your layout skills. If you're ready to move up from Junior challenges, this one is a great next step.",
        "imgURI": "/images/easy-bank/easybank.jpg",
        "location": "/easy-bank"
    },
    
]